
spring:
  datasource:
    druid:
      initial-size: 2
      max-active: 30
      min-idle: 5
      max-wait: 1000
      max-pool-prepared-statement-per-connection-size: 5
      validation-query: select 1
      validation-query-timeout: 1
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 30000
      async-close-connection-enable: true
    url: jdbc:mysql://127.0.0.1/pcrawler?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    generate-ddl: true
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 9001

